//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int TreningID { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateFinish { get; set; }
    }
}
