//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveGym.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymDbEntities : DbContext
    {
        public GymDbEntities()
            : base("name=GymDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Archive> Archives { get; set; }
        public virtual DbSet<Dimension> Dimensions { get; set; }
        public virtual DbSet<Exercis> Exercises { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<TreningExercis> TreningExercises { get; set; }
        public virtual DbSet<Trening> Trenings { get; set; }
        public virtual DbSet<UserPerformance> UserPerformances { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
