//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int weigth { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> dimensions_Id { get; set; }
        public Nullable<int> performance_id { get; set; }
    
        public virtual Dimension Dimension { get; set; }
        public virtual UserPerformance UserPerformance { get; set; }
    }
}
